<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>StyleLibrary</RootNamespace>
		<AssemblyName>StyleLibrary</AssemblyName>
	</PropertyGroup>

</Project>
